mower_data = [
    {
        "id": "726",
        "slug": "dixie-chopper-zee-2-2348kw",
        "name": "Zee 2 2348KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/residential/zee-2/",
    },
    {
        "id": "727",
        "slug": "dixie-chopper-zee-2-2354kw",
        "name": "Zee 2 2354KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/residential/zee-2/",
    },
    {
        "id": "730",
        "slug": "dixie-chopper-blackhawk-2454kw",
        "name": "BlackHawk 2454KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/blackhawk/",
    },
    {
        "id": "731",
        "slug": "dixie-chopper-blackhawk-2460kw",
        "name": "BlackHawk 2460KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/blackhawk/",
    },
    {
        "id": "732",
        "slug": "dixie-chopper-blackhawk-hp-2448kw",
        "name": "BlackHawk HP 2448KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/blackhawk-hp/",
    },
    {
        "id": "733",
        "slug": "dixie-chopper-blackhawk-hp-2454kw",
        "name": "BlackHawk HP 2454KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/blackhawk-hp/",
    },
    {
        "id": "728",
        "slug": "dixie-chopper-talon-r-c-2844vge",
        "name": "Talon R/C 2844VGE",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/remote-control/talon-rc/",
    },
    {
        "id": "725",
        "slug": "dixie-chopper-zee-2-2342kw",
        "name": "Zee 2 2342KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/residential/zee-2/",
    },
    {
        "id": "729",
        "slug": "dixie-chopper-blackhawk-2448kw",
        "name": "BlackHawk 2448KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/blackhawk/",
    },
    {
        "id": "739",
        "slug": "dixie-chopper-classic-4072vge",
        "name": "Classic 4072VGE",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/industrial/classic/",
    },
    {
        "id": "740",
        "slug": "dixie-chopper-eagle-2754kw",
        "name": "Eagle 2754KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/eagle/",
    },
    {
        "id": "734",
        "slug": "dixie-chopper-blackhawk-hp-2460kw",
        "name": "BlackHawk HP 2460KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/blackhawk-hp/",
    },
    {
        "id": "735",
        "slug": "dixie-chopper-classic-2760kw",
        "name": "Classic 2760KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/industrial/classic/",
    },
    {
        "id": "736",
        "slug": "dixie-chopper-classic-3560kw",
        "name": "Classic 3560KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/industrial/classic/",
    },
    {
        "id": "738",
        "slug": "dixie-chopper-classic-3572kw",
        "name": "Classic 3572KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/industrial/classic/",
    },
    {
        "id": "737",
        "slug": "dixie-chopper-classic-4060vge",
        "name": "Classic 4060VGE",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/industrial/classic/",
    },
    {
        "id": "742",
        "slug": "dixie-chopper-eagle-hp-3560kw",
        "name": "Eagle HP 3560KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/eagle-hp/",
    },
    {
        "id": "744",
        "slug": "dixie-chopper-eagle-hp-3572kw",
        "name": "Eagle HP 3572KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/eagle-hp/",
    },
    {
        "id": "745",
        "slug": "dixie-chopper-eagle-hp-4072vge",
        "name": "Eagle HP 4072VGE",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/eagle-hp/",
    },
    {
        "id": "743",
        "slug": "dixie-chopper-eagle-hp-4060vge",
        "name": "Eagle HP 4060VGE",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/eagle-hp/",
    },
    {
        "id": "756",
        "slug": "dixie-chopper-falcon-hp-2448kw",
        "name": "Falcon HP 2448KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/residential/falcon-hp/",
    },
    {
        "id": "750",
        "slug": "dixie-chopper-xcaliber-3566kw",
        "name": "Xcaliber 3566KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/industrial/xcaliber/",
    },
    {
        "id": "752",
        "slug": "dixie-chopper-xcaliber-3574kw",
        "name": "Xcaliber 3574KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/industrial/xcaliber/",
    },
    {
        "id": "751",
        "slug": "dixie-chopper-xcaliber-4066vge",
        "name": "Xcaliber 4066VGE",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/industrial/xcaliber/",
    },
    {
        "id": "741",
        "slug": "dixie-chopper-eagle-2760kw",
        "name": "Eagle 2760KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/eagle/",
    },
    {
        "id": "753",
        "slug": "dixie-chopper-xcaliber-4074vge",
        "name": "Xcaliber 4074VGE",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/industrial/xcaliber/",
    },
    {
        "id": "754",
        "slug": "dixie-chopper-zee-2-hp-series-2448kw",
        "name": "Zee 2 HP Series 2448KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/residential/zee-2-hp/",
    },
    {
        "id": "755",
        "slug": "dixie-chopper-zee-2-hp-series-2454kw",
        "name": "Zee 2 HP Series 2454KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/residential/zee-2-hp/",
    },
    {
        "id": "757",
        "slug": "dixie-chopper-falcon-hp-2454kw",
        "name": "Falcon HP 2454KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/residential/falcon-hp/",
    },
    {
        "id": "746",
        "slug": "dixie-chopper-falcon-hpx-2448kw",
        "name": "Falcon HPX 2448KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/falcon-hpx/",
    },
    {
        "id": "747",
        "slug": "dixie-chopper-falcon-hpx-2454kw",
        "name": "Falcon HPX 2454KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/falcon-hpx/",
    },
    {
        "id": "758",
        "slug": "dixie-chopper-falcon-hp-2460kw",
        "name": "Falcon HP 2460KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/residential/falcon-hp/",
    },
    {
        "id": "748",
        "slug": "dixie-chopper-falcon-hpx-2460kw",
        "name": "Falcon HPX 2460KW",
        "brand_name": "Dixie Chopper",
        "page_url": "",
        "category_page_url": "",
        "series_page_url": "https://www.dixiechopper.com/product-category/commercial/falcon-hpx/",
    },
]

mower_data = [
    {
        "id": "941",
        "slug": "snapper-7800982b",
        "name": "7800982B",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/push-mowers/hi-vac-lawn-mower.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/push-mowers/hi-vac-lawn-mower.html",
        "series_page_url": "",
    },
    {
        "id": "942",
        "slug": "snapper-7800981b",
        "name": "7800981B",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/push-mowers/ninja-push-mowers.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/push-mowers/ninja-push-mowers.html",
        "series_page_url": "",
    },
    {
        "id": "943",
        "slug": "snapper-7800849b",
        "name": "7800849B",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/push-mowers/commercial-walk-mowers.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/push-mowers/commercial-walk-mowers.html",
        "series_page_url": "",
    },
    {
        "id": "947",
        "slug": "snapper-2691499",
        "name": "2691499",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/zero-turn-mowers/360z-zero-turn-mower.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/zero-turn-mowers/360z-zero-turn-mower.html",
        "series_page_url": "",
    },
    {
        "id": "948",
        "slug": "snapper-2691651",
        "name": "2691651",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/zero-turn-mowers/360z-zero-turn-mower.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/zero-turn-mowers/360z-zero-turn-mower.html",
        "series_page_url": "",
    },
    {
        "id": "949",
        "slug": "snapper-2691827",
        "name": "2691827",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/zero-turn-mowers/360z-zero-turn-mower.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/zero-turn-mowers/360z-zero-turn-mower.html",
        "series_page_url": "",
    },
    {
        "id": "950",
        "slug": "snapper-2691829",
        "name": "2691829",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/zero-turn-mowers/360z-zero-turn-mower.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/zero-turn-mowers/360z-zero-turn-mower.html",
        "series_page_url": "",
    },
    {
        "id": "940",
        "slug": "snapper-7800980b",
        "name": "7800980B",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/push-mowers/hi-vac-lawn-mower.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/push-mowers/hi-vac-lawn-mower.html",
        "series_page_url": "",
    },
    {
        "id": "944",
        "slug": "snapper-7800968b",
        "name": "7800968B",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/push-mowers/commercial-walk-mowers.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/push-mowers/commercial-walk-mowers.html",
        "series_page_url": "",
    },
    {
        "id": "945",
        "slug": "snapper-2691663",
        "name": "2691663",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/riding-mowers/spx-riding-mower.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/riding-mowers/spx-riding-mower.html",
        "series_page_url": "",
    },
    {
        "id": "946",
        "slug": "snapper-2691664",
        "name": "2691664",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/riding-mowers/spx-riding-mower.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/riding-mowers/spx-riding-mower.html",
        "series_page_url": "",
    },
    {
        "id": "951",
        "slug": "snapper-2691816",
        "name": "2691816",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/zero-turn-mowers/360z-xt-zero-turn-mower.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/zero-turn-mowers/360z-xt-zero-turn-mower.html",
        "series_page_url": "",
    },
    {
        "id": "953",
        "slug": "snapper-5901862",
        "name": "5901862",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s120.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s120.html",
        "series_page_url": "",
    },
    {
        "id": "952",
        "slug": "snapper-2691817",
        "name": "2691817",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/zero-turn-mowers/360z-xt-zero-turn-mower.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/zero-turn-mowers/360z-xt-zero-turn-mower.html",
        "series_page_url": "",
    },
    {
        "id": "954",
        "slug": "snapper-5901865",
        "name": "5901865",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s120.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s120.html",
        "series_page_url": "",
    },
    {
        "id": "955",
        "slug": "snapper-5901867",
        "name": "5901867",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s120.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s120.html",
        "series_page_url": "",
    },
    {
        "id": "956",
        "slug": "snapper-5901868",
        "name": "5901868",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s120.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s120.html",
        "series_page_url": "",
    },
    {
        "id": "957",
        "slug": "snapper-5901280",
        "name": "5901280",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s200xt.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s200xt.html",
        "series_page_url": "",
    },
    {
        "id": "958",
        "slug": "snapper-5901664",
        "name": "5901664",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s200xt.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s200xt.html",
        "series_page_url": "",
    },
    {
        "id": "959",
        "slug": "snapper-5901665",
        "name": "5901665",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s200xt.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s200xt.html",
        "series_page_url": "",
    },
    {
        "id": "963",
        "slug": "snapper-82v-max-cordless-self-propelled-walk-mower",
        "name": "82V MAX CORDLESS SELF-PROPELLED WALK MOWER",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/electric-products/mowers/snapper-xd-82v-max-electric-cordless-self-propelled-walk-mower.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/electric-products/mowers/snapper-xd-82v-max-electric-cordless-self-propelled-walk-mower.html",
        "series_page_url": "",
    },
    {
        "id": "964",
        "slug": "snapper-82v-max-stepsense-cordless-lawn-mower",
        "name": "82V MAX STEPSENSE CORDLESS LAWN MOWER",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/electric-products/mowers/snapper-xd-82v-max-stepsense-automatic-drive-electric-lawn-mower.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/electric-products/mowers/snapper-xd-82v-max-stepsense-automatic-drive-electric-lawn-mower.html",
        "series_page_url": "",
    },
    {
        "id": "960",
        "slug": "snapper-5901666",
        "name": "5901666",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s200xt.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s200xt.html",
        "series_page_url": "",
    },
    {
        "id": "961",
        "slug": "snapper-5901667",
        "name": "5901667",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s200xt.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/pro/zero-turn-mowers/s200xt.html",
        "series_page_url": "",
    },
    {
        "id": "962",
        "slug": "snapper-82v-max-cordless-walk-mowers",
        "name": "82V MAX CORDLESS WALK MOWERS",
        "brand_name": "Snapper",
        "page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/electric-products/mowers/82volt-max_-lithiumion-cordless-walk-mowers.html",
        "category_page_url": "https://www.snapper.com/na/en_us/product-catalog/residential/electric-products/mowers/82volt-max_-lithiumion-cordless-walk-mowers.html",
        "series_page_url": "",
    },
]
