mower_data = [
{"id":"1320","slug":"kubota-z242kh-48","name":"Z242KH-48","brand_name":"Kubota","page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers/z242kh-48","category_page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers","series_page_url":""},
{"id":"1312","slug":"kubota-sz19nc-36-2","name":"SZ19NC-36-2","brand_name":"Kubota","page_url":"https://www.kubotausa.com/products/mowers/stand-on-mowers/sz19nc-36-2","category_page_url":"https://www.kubotausa.com/products/mowers/stand-on-mowers","series_page_url":""},
{"id":"1319","slug":"kubota-z232kw-42","name":"Z232KW-42","brand_name":"Kubota","page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers/z232kw-42","category_page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers","series_page_url":""},
{"id":"1326","slug":"kubota-z421kwnc-54","name":"Z421KWNC-54","brand_name":"Kubota","page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers/z421kw-3-54","category_page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers","series_page_url":""},
{"id":"1343","slug":"kubota-zd1011","name":"ZD1011","brand_name":"Kubota","page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers/zd1011","category_page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers","series_page_url":""},
{"id":"1324","slug":"kubota-z411kwnc-48","name":"Z411KWNC-48","brand_name":"Kubota","page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers/z411kw-3-48","category_page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers","series_page_url":""},
{"id":"1332","slug":"kubota-z723kh-3-48","name":"Z723KH-3-48","brand_name":"Kubota","page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers/z723kh-3-48","category_page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers","series_page_url":""},
{"id":"1333","slug":"kubota-z724khnc-54","name":"Z724KHNC-54","brand_name":"Kubota","page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers/z724kh-3-54","category_page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers","series_page_url":""},
{"id":"1334","slug":"kubota-z724xkwnc-48","name":"Z724XKWNC-48","brand_name":"Kubota","page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers/z724xkw-3-48","category_page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers","series_page_url":""},
{"id":"1337","slug":"kubota-z726xkwnc-60","name":"Z726XKWNC-60","brand_name":"Kubota","page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers/z726xkw-3-60","category_page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers","series_page_url":""},
{"id":"1340","slug":"kubota-z781kwi-54","name":"Z781KWi-54","brand_name":"Kubota","page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers/z781kwi29-54","category_page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers","series_page_url":""},
{"id":"1347","slug":"kubota-zd1611","name":"ZD1611","brand_name":"Kubota","page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers/zd1611","category_page_url":"https://www.kubotausa.com/products/mowers/zero-turn-mowers","series_page_url":""}
] # VPN Blocked

mower_data = [
{"id":"1285","slug":"swisher-wrc11524cl","name":"WRC11524CL","brand_name":"Swisher","page_url":"https://www.swisherinc.com/classic-11-5hp-24-in-briggs-stratton-walk-behind-rough-cut.html","category_page_url":"https://www.swisherinc.com/categories/walk-behind-mowers.html","series_page_url":""},
{"id":"1286","slug":"swisher-wrc11524bs","name":"WRC11524BS","brand_name":"Swisher","page_url":"https://www.swisherinc.com/11-5hp-24-in-briggs-stratton-walk-behind-rough-cut.html","category_page_url":"https://www.swisherinc.com/categories/walk-behind-mowers.html","series_page_url":""},
{"id":"1287","slug":"swisher-wrc11524bsc","name":"WRC11524BSC","brand_name":"Swisher","page_url":"https://www.swisherinc.com/categories/walk-behind-mowers/11-5hp-24-in-briggs-stratton-walk-behind-rough-cut-with-casters.html","category_page_url":"https://www.swisherinc.com/categories/walk-behind-mowers.html","series_page_url":""},
{"id":"1288","slug":"swisher-ztr2460bs-ca","name":"ZTR2460BS-CA","brand_name":"Swisher","page_url":"https://www.swisherinc.com/categories/zero-turn-mowers/ztr2460bs-ca-swisherr-24-hp-60-b-s-zero-turn-rider-free-shipping.html","category_page_url":"https://www.swisherinc.com/categories/zero-turn-mowers.html","series_page_url":""}
] # bad quality images

mower_data = [
{"id":"632","slug":"exmark-kawasaki-fx1000v-with-60-in-ultracut-series-6-deck","name":"Kawasaki FX1000V with 60-in UltraCut Series 6 Deck","brand_name":"Exmark","page_url":"https://www.exmark.com/mowers/stand-on/vertex/vertex-x-series/vxx999eka60600","category_page_url":"","series_page_url":"https://www.exmark.com/mowers/stand-on/vertex/"},
{"id":"623","slug":"exmark-kawasaki-fx730v-with-48-in-ultracut-series-4-deck","name":"Kawasaki FX730V with 48-in UltraCut Series 4 Deck","brand_name":"Exmark","page_url":"https://www.exmark.com/mowers/stand-on/vertex/vertex-s-series/vxs730gka48400","category_page_url":"","series_page_url":"https://www.exmark.com/mowers/stand-on/vertex/"},
{"id":"626","slug":"exmark-kohler-efi-ecv740-with-48-in-ultracut-series-4-deck","name":"Kohler EFI ECV740 with 48-in UltraCut Series 4 Deck","brand_name":"Exmark","page_url":"https://www.exmark.com/mowers/stand-on/vertex/vertex-s-series/vxs740ekc48400","category_page_url":"","series_page_url":"https://www.exmark.com/mowers/stand-on/vertex/"}
] # get's images from cdn

mower_data = [
{"id":"726","slug":"dixie-chopper-zee-2-2348kw","name":"Zee 2 2348KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/residential/zee-2/"},
{"id":"727","slug":"dixie-chopper-zee-2-2354kw","name":"Zee 2 2354KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/residential/zee-2/"},
{"id":"730","slug":"dixie-chopper-blackhawk-2454kw","name":"BlackHawk 2454KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/blackhawk/"},
{"id":"731","slug":"dixie-chopper-blackhawk-2460kw","name":"BlackHawk 2460KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/blackhawk/"},
{"id":"732","slug":"dixie-chopper-blackhawk-hp-2448kw","name":"BlackHawk HP 2448KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/blackhawk-hp/"},
{"id":"733","slug":"dixie-chopper-blackhawk-hp-2454kw","name":"BlackHawk HP 2454KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/blackhawk-hp/"},
{"id":"728","slug":"dixie-chopper-talon-r-c-2844vge","name":"Talon R/C 2844VGE","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/remote-control/talon-rc/"},
{"id":"725","slug":"dixie-chopper-zee-2-2342kw","name":"Zee 2 2342KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/residential/zee-2/"},
{"id":"729","slug":"dixie-chopper-blackhawk-2448kw","name":"BlackHawk 2448KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/blackhawk/"},
{"id":"739","slug":"dixie-chopper-classic-4072vge","name":"Classic 4072VGE","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/industrial/classic/"},
{"id":"740","slug":"dixie-chopper-eagle-2754kw","name":"Eagle 2754KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/eagle/"},
{"id":"734","slug":"dixie-chopper-blackhawk-hp-2460kw","name":"BlackHawk HP 2460KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/blackhawk-hp/"},
{"id":"735","slug":"dixie-chopper-classic-2760kw","name":"Classic 2760KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/industrial/classic/"},
{"id":"736","slug":"dixie-chopper-classic-3560kw","name":"Classic 3560KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/industrial/classic/"},
{"id":"738","slug":"dixie-chopper-classic-3572kw","name":"Classic 3572KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/industrial/classic/"},
{"id":"737","slug":"dixie-chopper-classic-4060vge","name":"Classic 4060VGE","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/industrial/classic/"},
{"id":"742","slug":"dixie-chopper-eagle-hp-3560kw","name":"Eagle HP 3560KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/eagle-hp/"},
{"id":"744","slug":"dixie-chopper-eagle-hp-3572kw","name":"Eagle HP 3572KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/eagle-hp/"},
{"id":"745","slug":"dixie-chopper-eagle-hp-4072vge","name":"Eagle HP 4072VGE","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/eagle-hp/"},
{"id":"743","slug":"dixie-chopper-eagle-hp-4060vge","name":"Eagle HP 4060VGE","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/eagle-hp/"},
{"id":"756","slug":"dixie-chopper-falcon-hp-2448kw","name":"Falcon HP 2448KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/residential/falcon-hp/"},
{"id":"750","slug":"dixie-chopper-xcaliber-3566kw","name":"Xcaliber 3566KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/industrial/xcaliber/"},
{"id":"752","slug":"dixie-chopper-xcaliber-3574kw","name":"Xcaliber 3574KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/industrial/xcaliber/"},
{"id":"751","slug":"dixie-chopper-xcaliber-4066vge","name":"Xcaliber 4066VGE","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/industrial/xcaliber/"},
{"id":"741","slug":"dixie-chopper-eagle-2760kw","name":"Eagle 2760KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/eagle/"},
{"id":"753","slug":"dixie-chopper-xcaliber-4074vge","name":"Xcaliber 4074VGE","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/industrial/xcaliber/"},
{"id":"754","slug":"dixie-chopper-zee-2-hp-series-2448kw","name":"Zee 2 HP Series 2448KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/residential/zee-2-hp/"},
{"id":"755","slug":"dixie-chopper-zee-2-hp-series-2454kw","name":"Zee 2 HP Series 2454KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/residential/zee-2-hp/"},
{"id":"757","slug":"dixie-chopper-falcon-hp-2454kw","name":"Falcon HP 2454KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/residential/falcon-hp/"},
{"id":"746","slug":"dixie-chopper-falcon-hpx-2448kw","name":"Falcon HPX 2448KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/falcon-hpx/"},
{"id":"747","slug":"dixie-chopper-falcon-hpx-2454kw","name":"Falcon HPX 2454KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/falcon-hpx/"},
{"id":"758","slug":"dixie-chopper-falcon-hp-2460kw","name":"Falcon HP 2460KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/residential/falcon-hp/"},
{"id":"748","slug":"dixie-chopper-falcon-hpx-2460kw","name":"Falcon HPX 2460KW","brand_name":"Dixie Chopper","page_url":"","category_page_url":"","series_page_url":"https://www.dixiechopper.com/product-category/commercial/falcon-hpx/"}
] # images not fetched.
