mower_data = [
    {
        "id": "969",
        "slug": "ferris-5902094",
        "name": "5902094",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/electric/300e-zero-turn-mower.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "972",
        "slug": "ferris-5902056",
        "name": "5902056",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/500s-zero-turn-mower.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "984",
        "slug": "ferris-5901891",
        "name": "5901891",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/walk-behind-mowers/fw45-walk-behind-mowers.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "985",
        "slug": "ferris-5902015",
        "name": "5902015",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/walk-behind-mowers/fw45-walk-behind-mowers.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "986",
        "slug": "ferris-5901892",
        "name": "5901892",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/walk-behind-mowers/fw45-walk-behind-mowers.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "988",
        "slug": "ferris-5902016",
        "name": "5902016",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/walk-behind-mowers/fw45-walk-behind-mowers.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "999",
        "slug": "ferris-5902159",
        "name": "5902159",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/isx-2200-zero-turn-mowers.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "1002",
        "slug": "ferris-5902064",
        "name": "5902064",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/isx-3300-zero-turn-mowers.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "966",
        "slug": "ferris-5902206",
        "name": "5902206",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/300s-zero-turn-mower.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "967",
        "slug": "ferris-5902207",
        "name": "5902207",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/300s-zero-turn-mower.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "968",
        "slug": "ferris-5902093",
        "name": "5902093",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/electric/300e-zero-turn-mower.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "971",
        "slug": "ferris-5902102",
        "name": "5902102",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/500s-zero-turn-mower.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "973",
        "slug": "ferris-5902103",
        "name": "5902103",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/500s-zero-turn-mower.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "987",
        "slug": "ferris-5901893",
        "name": "5901893",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/walk-behind-mowers/fw45-walk-behind-mowers.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "998",
        "slug": "ferris-5902157",
        "name": "5902157",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/isx-2200-zero-turn-mowers.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "1000",
        "slug": "ferris-5902180",
        "name": "5902180",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/isx-2200-zero-turn-mowers.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "1004",
        "slug": "ferris-5902160",
        "name": "5902160",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/isx-3300-zero-turn-mowers.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "1003",
        "slug": "ferris-5902145",
        "name": "5902145",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/isx-3300-zero-turn-mowers.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "1006",
        "slug": "ferris-5902074",
        "name": "5902074",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/isx-800-zero-turn-mower.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "1007",
        "slug": "ferris-5902075",
        "name": "5902075",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/isx-800-zero-turn-mower.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "1008",
        "slug": "ferris-5902154",
        "name": "5902154",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/isx-800-zero-turn-mower.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "1009",
        "slug": "ferris-5902155",
        "name": "5902155",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/isx-800-zero-turn-mower.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "1010",
        "slug": "ferris-5902172",
        "name": "5902172",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/zero-turn-mowers/isx-800-zero-turn-mower.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "1011",
        "slug": "ferris-5900533",
        "name": "5900533",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/front-mount-lawn-mowers/procut-s.html",
        "category_page_url": "",
        "series_page_url": "",
    },
    {
        "id": "1012",
        "slug": "ferris-5902106",
        "name": "5902106",
        "brand_name": "Ferris",
        "page_url": "https://www.ferrismowers.com/na/en_us/product-catalog/front-mount-lawn-mowers/procut-s.html",
        "category_page_url": "",
        "series_page_url": "",
    },
]

if __name__ == "__main__":
    for idx,mower in enumerate(mower_data):
        if mower["name"] == '5902145':
            print(idx)
            break

